name: Update Readme
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
      
jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKA_GH_TOKEN }}
          
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_TIMEZONE: True
          SHOW_EDITORS: True
          SHOW_LANGUAGE_PER_REPO: True
          
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
